version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: wj_keycloak
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - 8888:8080
