version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_VENDOR: h2
    ports:
      - 8888:8080


